baseURL = "http://mkcee.com"
builddrafts = true
canonifyurls = true
editor = "vim"
languageCode = "en-us"
newContentEditor = "vim"
publishdir = "dist"
theme = "pixyll"
title = "M.K.C."

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Tesla's Awesome Hugo Site"
  author = "Nikola Tesla"
