baseURL = "http://mkcee.com"
builddrafts = true
canonifyurls = true
editor = "vim"
languageCode = "en-us"
newContentEditor = "vim"
publishdir = "dist"
theme = "pixyll"
title = "M.K.C."
author = "Mok Ka Chun"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "M.K.C.'s Awesome Personal Site"
  author = "Mok Ka Chun"
  google_analytics_id = "UA-64777923-1"
  disqus_shortname = "mkcee"
  paginate = true
